steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "gcr.io/immersion-rc-proxy/github.com/kayvank/guest-book:v1.0-SNAPSHOT-$SHORT_SHA", "."]
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/immersion-rc-proxy/github.com/kayvank/guest-book:v1.0-SNAPSHOT-$SHORT_SHA"]
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - "-n"
  - "dev"
  - "set"
  - "image"
  - "deployment.v1.apps/guest-book"
  - "guest-book= gcr.io/immersion-rc-proxy/github.com/kayvank/guest-book:v1.0-SNAPSHOT-$SHORT_SHA"
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-east1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=guest-book'
