apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: q2io-llc
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: kayvan@q2io.com
    privateKeySecretRef:
      name: tls-letsencrypt-q2io-llc
    http01: {}
